language: python
python:
  - 3.6

install:
    - pip install numpy
    - pip install scipy
    - pip install matplotlib
    - pip install cvxopt
    - pip install cvxpy

script:
    - python --version
    - ./test_run.sh

